_target_: diffusion_policy.workspace.train_robomimic_lowdim_workspace.TrainRobomimicLowdimWorkspace
action_dim: 7
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
    k: 5
    mode: max
    monitor_key: test_mean_score
dataloader:
  batch_size: 256
  num_workers: 1
  persistent_workers: false
  pin_memory: true
  shuffle: true
exp_name: default
horizon: 10
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: 2022.12.30-01.51.28_train_robomimic_lowdim_square_lowdim
  project: diffusion_policy_debug
  tags:
  - train_robomimic_lowdim
  - square_lowdim
  - default
multi_run:
  run_dir: data/outputs/2022.12.30/01.51.28_train_robomimic_lowdim_square_lowdim
  wandb_name_base: 2022.12.30-01.51.28_train_robomimic_lowdim_square_lowdim
n_action_steps: 1
n_latency_steps: 0
n_obs_steps: 1
name: train_robomimic_lowdim
obs_dim: 23
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.robomimic_lowdim_policy.RobomimicLowdimPolicy
  action_dim: 7
  algo_name: bc_rnn
  dataset_type: mh
  obs_dim: 23
  obs_type: low_dim
  task_name: square
task:
  abs_action: false
  action_dim: 7
  dataset:
    _target_: diffusion_policy.dataset.robomimic_replay_lowdim_dataset.RobomimicReplayLowdimDataset
    abs_action: false
    dataset_path: data/robomimic/datasets/square/mh/low_dim.hdf5
    horizon: 10
    obs_keys:
    - object
    - robot0_eef_pos
    - robot0_eef_quat
    - robot0_gripper_qpos
    pad_after: 0
    pad_before: 0
    seed: 42
    val_ratio: 0.02
  dataset_path: data/robomimic/datasets/square/mh/low_dim.hdf5
  dataset_type: mh
  env_runner:
    _target_: diffusion_policy.env_runner.robomimic_lowdim_runner.RobomimicLowdimRunner
    abs_action: false
    crf: 22
    dataset_path: data/robomimic/datasets/square/mh/low_dim.hdf5
    fps: 10
    max_steps: 500
    n_action_steps: 1
    n_envs: 28
    n_latency_steps: 0
    n_obs_steps: 1
    n_test: 50
    n_test_vis: 4
    n_train: 6
    n_train_vis: 2
    obs_keys:
    - object
    - robot0_eef_pos
    - robot0_eef_quat
    - robot0_gripper_qpos
    past_action: false
    render_hw:
    - 128
    - 128
    test_start_seed: 100000
    train_start_idx: 0
  keypoint_dim: 3
  name: square_lowdim
  obs_dim: 23
  obs_keys:
  - object
  - robot0_eef_pos
  - robot0_eef_quat
  - robot0_gripper_qpos
  task_name: square
task_name: square_lowdim
training:
  checkpoint_every: 50
  debug: false
  device: cuda:0
  max_train_steps: null
  max_val_steps: null
  num_epochs: 8000
  rollout_every: 50
  seed: 42
  tqdm_interval_sec: 1.0
  val_every: 1
transition_dim: 30
val_dataloader:
  batch_size: 256
  num_workers: 1
  persistent_workers: false
  pin_memory: true
  shuffle: false
