_target_: diffusion_policy.workspace.train_diffusion_unet_lowdim_workspace.TrainDiffusionUnetLowdimWorkspace
action_dim: 20
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
    k: 5
    mode: max
    monitor_key: test_mean_score
dataloader:
  batch_size: 256
  num_workers: 1
  persistent_workers: false
  pin_memory: true
  shuffle: true
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: obs_global_rerun
horizon: 16
keypoint_dim: 3
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: 2023.02.23-19.48.20_train_diffusion_unet_lowdim_transport_lowdim
  project: diffusion_policy_debug
  resume: true
  tags:
  - train_diffusion_unet_lowdim
  - transport_lowdim
  - obs_global_rerun
multi_run:
  run_dir: data/outputs/2023.02.23/19.48.20_train_diffusion_unet_lowdim_transport_lowdim
  wandb_name_base: 2023.02.23-19.48.20_train_diffusion_unet_lowdim_transport_lowdim
n_action_steps: 8
n_latency_steps: 0
n_obs_steps: 2
name: train_diffusion_unet_lowdim
obs_as_global_cond: true
obs_as_local_cond: false
obs_dim: 59
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.diffusion_unet_lowdim_policy.DiffusionUnetLowdimPolicy
  action_dim: 20
  horizon: 16
  model:
    _target_: diffusion_policy.model.diffusion.conditional_unet1d.ConditionalUnet1D
    cond_predict_scale: true
    diffusion_step_embed_dim: 256
    down_dims:
    - 256
    - 512
    - 1024
    global_cond_dim: 118
    input_dim: 20
    kernel_size: 5
    local_cond_dim: null
    n_groups: 8
  n_action_steps: 8
  n_obs_steps: 2
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    beta_start: 0.0001
    clip_sample: true
    num_train_timesteps: 100
    prediction_type: epsilon
    variance_type: fixed_small
  num_inference_steps: 100
  oa_step_convention: true
  obs_as_global_cond: true
  obs_as_local_cond: false
  obs_dim: 59
  pred_action_steps_only: false
pred_action_steps_only: false
task:
  abs_action: true
  action_dim: 20
  dataset:
    _target_: diffusion_policy.dataset.robomimic_replay_lowdim_dataset.RobomimicReplayLowdimDataset
    abs_action: true
    dataset_path: data/robomimic/datasets/transport/ph/low_dim_abs.hdf5
    horizon: 16
    obs_keys:
    - object
    - robot0_eef_pos
    - robot0_eef_quat
    - robot0_gripper_qpos
    - robot1_eef_pos
    - robot1_eef_quat
    - robot1_gripper_qpos
    pad_after: 7
    pad_before: 1
    seed: 42
    use_legacy_normalizer: false
    val_ratio: 0.02
  dataset_path: data/robomimic/datasets/transport/ph/low_dim_abs.hdf5
  dataset_type: ph
  env_runner:
    _target_: diffusion_policy.env_runner.robomimic_lowdim_runner.RobomimicLowdimRunner
    abs_action: true
    crf: 22
    dataset_path: data/robomimic/datasets/transport/ph/low_dim_abs.hdf5
    fps: 10
    max_steps: 700
    n_action_steps: 8
    n_envs: 28
    n_latency_steps: 0
    n_obs_steps: 2
    n_test: 50
    n_test_vis: 4
    n_train: 6
    n_train_vis: 2
    obs_keys:
    - object
    - robot0_eef_pos
    - robot0_eef_quat
    - robot0_gripper_qpos
    - robot1_eef_pos
    - robot1_eef_quat
    - robot1_gripper_qpos
    past_action: false
    render_hw:
    - 128
    - 128
    test_start_seed: 100000
    train_start_idx: 0
  keypoint_dim: 3
  name: transport_lowdim
  obs_dim: 59
  obs_keys:
  - object
  - robot0_eef_pos
  - robot0_eef_quat
  - robot0_gripper_qpos
  - robot1_eef_pos
  - robot1_eef_quat
  - robot1_gripper_qpos
  task_name: transport
task_name: transport_lowdim
training:
  checkpoint_every: 50
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 5000
  resume: true
  rollout_every: 50
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 1
val_dataloader:
  batch_size: 256
  num_workers: 1
  persistent_workers: false
  pin_memory: true
  shuffle: false
