_target_: diffusion_policy.workspace.train_bet_lowdim_workspace.TrainBETLowdimWorkspace
action_dim: 14
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
    k: 5
    mode: max
    monitor_key: test_mean_score
dataloader:
  batch_size: 256
  num_workers: 1
  persistent_workers: false
  pin_memory: true
  shuffle: true
exp_name: default
horizon: 10
keypoint_dim: 3
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: 2022.12.28-22.19.57_train_bet_lowdim_transport_lowdim
  project: diffusion_policy_debug
  tags:
  - train_bet_lowdim
  - transport_lowdim
  - default
multi_run:
  run_dir: data/outputs/2022.12.28/22.19.57_train_bet_lowdim_transport_lowdim
  wandb_name_base: 2022.12.28-22.19.57_train_bet_lowdim_transport_lowdim
n_action_steps: 8
n_latency_steps: 0
n_obs_steps: 2
name: train_bet_lowdim
obs_as_global_cond: false
obs_as_local_cond: false
obs_dim: 59
optimizer:
  betas:
  - 0.9
  - 0.95
  learning_rate: 0.0001
  weight_decay: 0.1
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.bet_lowdim_policy.BETLowdimPolicy
  action_ae:
    _target_: diffusion_policy.model.bet.action_ae.discretizers.k_means.KMeansDiscretizer
    action_dim: 14
    num_bins: 24
    predict_offsets: true
  horizon: 10
  n_action_steps: 8
  n_obs_steps: 2
  obs_encoding_net:
    _target_: torch.nn.Identity
    output_dim: 59
  state_prior:
    _target_: diffusion_policy.model.bet.latent_generators.mingpt.MinGPT
    action_dim: 14
    block_size: 10
    discrete_input: false
    focal_loss_gamma: 2.0
    input_dim: 59
    n_embd: 72
    n_head: 4
    n_layer: 4
    offset_loss_scale: 1000.0
    predict_offsets: true
    vocab_size: 24
pred_action_steps_only: false
task:
  abs_action: false
  action_dim: 14
  dataset:
    _target_: diffusion_policy.dataset.robomimic_replay_lowdim_dataset.RobomimicReplayLowdimDataset
    abs_action: false
    dataset_path: data/robomimic/datasets/transport/ph/low_dim.hdf5
    horizon: 10
    obs_keys:
    - object
    - robot0_eef_pos
    - robot0_eef_quat
    - robot0_gripper_qpos
    - robot1_eef_pos
    - robot1_eef_quat
    - robot1_gripper_qpos
    pad_after: 7
    pad_before: 1
    seed: 42
    val_ratio: 0.02
  dataset_path: data/robomimic/datasets/transport/ph/low_dim.hdf5
  dataset_type: ph
  env_runner:
    _target_: diffusion_policy.env_runner.robomimic_lowdim_runner.RobomimicLowdimRunner
    abs_action: false
    crf: 22
    dataset_path: data/robomimic/datasets/transport/ph/low_dim.hdf5
    fps: 10
    max_steps: 700
    n_action_steps: 8
    n_envs: 28
    n_latency_steps: 0
    n_obs_steps: 2
    n_test: 50
    n_test_vis: 5
    n_train: 6
    n_train_vis: 2
    obs_keys:
    - object
    - robot0_eef_pos
    - robot0_eef_quat
    - robot0_gripper_qpos
    - robot1_eef_pos
    - robot1_eef_quat
    - robot1_gripper_qpos
    past_action: false
    render_hw:
    - 128
    - 128
    test_start_seed: 100000
    train_start_idx: 0
  keypoint_dim: 3
  name: transport_lowdim
  obs_dim: 59
  obs_keys:
  - object
  - robot0_eef_pos
  - robot0_eef_quat
  - robot0_gripper_qpos
  - robot1_eef_pos
  - robot1_eef_quat
  - robot1_gripper_qpos
  task_name: transport
task_name: transport_lowdim
training:
  checkpoint_every: 50
  debug: false
  device: cuda:0
  enable_normalizer: true
  grad_norm_clip: 1.0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 8000
  rollout_every: 50
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  val_every: 1
val_dataloader:
  batch_size: 256
  num_workers: 1
  persistent_workers: false
  pin_memory: true
  shuffle: false
