_target_: diffusion_policy.workspace.train_ibc_dfo_hybrid_workspace.TrainIbcDfoHybridWorkspace
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
    k: 5
    mode: max
    monitor_key: test_mean_score
dataloader:
  batch_size: 128
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: true
dataset_obs_steps: 2
exp_name: default
horizon: 2
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: 2023.01.14-15.24.38_train_ibc_dfo_hybrid_transport_image
  project: diffusion_policy_debug
  resume: true
  tags:
  - train_ibc_dfo_hybrid
  - transport_image
  - default
multi_run:
  run_dir: data/outputs/2023.01.14/15.24.38_train_ibc_dfo_hybrid_transport_image
  wandb_name_base: 2023.01.14-15.24.38_train_ibc_dfo_hybrid_transport_image
n_action_steps: 1
n_latency_steps: 0
n_obs_steps: 2
name: train_ibc_dfo_hybrid
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.ibc_dfo_hybrid_image_policy.IbcDfoHybridImagePolicy
  andy_train: false
  crop_shape:
  - 76
  - 76
  dropout: 0.1
  eval_fixed_crop: true
  horizon: 2
  kevin_inference: false
  n_action_steps: 1
  n_obs_steps: 2
  obs_encoder_group_norm: true
  pred_n_iter: 5
  pred_n_samples: 1024
  shape_meta:
    action:
      shape:
      - 14
    obs:
      robot0_eef_pos:
        shape:
        - 3
      robot0_eef_quat:
        shape:
        - 4
      robot0_eye_in_hand_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      robot0_gripper_qpos:
        shape:
        - 2
      robot1_eef_pos:
        shape:
        - 3
      robot1_eef_quat:
        shape:
        - 4
      robot1_eye_in_hand_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      robot1_gripper_qpos:
        shape:
        - 2
      shouldercamera0_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      shouldercamera1_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
  train_n_neg: 1024
shape_meta:
  action:
    shape:
    - 14
  obs:
    robot0_eef_pos:
      shape:
      - 3
    robot0_eef_quat:
      shape:
      - 4
    robot0_eye_in_hand_image:
      shape:
      - 3
      - 84
      - 84
      type: rgb
    robot0_gripper_qpos:
      shape:
      - 2
    robot1_eef_pos:
      shape:
      - 3
    robot1_eef_quat:
      shape:
      - 4
    robot1_eye_in_hand_image:
      shape:
      - 3
      - 84
      - 84
      type: rgb
    robot1_gripper_qpos:
      shape:
      - 2
    shouldercamera0_image:
      shape:
      - 3
      - 84
      - 84
      type: rgb
    shouldercamera1_image:
      shape:
      - 3
      - 84
      - 84
      type: rgb
task:
  abs_action: false
  dataset:
    _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
    abs_action: false
    dataset_path: data/robomimic/datasets/transport/mh/image.hdf5
    horizon: 2
    n_obs_steps: 2
    pad_after: 0
    pad_before: 1
    rotation_rep: rotation_6d
    seed: 42
    shape_meta:
      action:
        shape:
        - 14
      obs:
        robot0_eef_pos:
          shape:
          - 3
        robot0_eef_quat:
          shape:
          - 4
        robot0_eye_in_hand_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        robot0_gripper_qpos:
          shape:
          - 2
        robot1_eef_pos:
          shape:
          - 3
        robot1_eef_quat:
          shape:
          - 4
        robot1_eye_in_hand_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        robot1_gripper_qpos:
          shape:
          - 2
        shouldercamera0_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        shouldercamera1_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
    use_cache: true
    use_legacy_normalizer: false
    val_ratio: 0.02
  dataset_path: data/robomimic/datasets/transport/mh/image.hdf5
  dataset_type: mh
  env_runner:
    _target_: diffusion_policy.env_runner.robomimic_image_runner.RobomimicImageRunner
    abs_action: false
    crf: 22
    dataset_path: data/robomimic/datasets/transport/mh/image.hdf5
    fps: 10
    max_steps: 700
    n_action_steps: 1
    n_envs: 28
    n_obs_steps: 2
    n_test: 50
    n_test_vis: 4
    n_train: 6
    n_train_vis: 2
    past_action: false
    render_obs_key: shouldercamera0_image
    shape_meta:
      action:
        shape:
        - 14
      obs:
        robot0_eef_pos:
          shape:
          - 3
        robot0_eef_quat:
          shape:
          - 4
        robot0_eye_in_hand_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        robot0_gripper_qpos:
          shape:
          - 2
        robot1_eef_pos:
          shape:
          - 3
        robot1_eef_quat:
          shape:
          - 4
        robot1_eye_in_hand_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        robot1_gripper_qpos:
          shape:
          - 2
        shouldercamera0_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        shouldercamera1_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
    test_start_seed: 100000
    tqdm_interval_sec: 1.0
    train_start_idx: 0
  name: transport_image
  shape_meta:
    action:
      shape:
      - 14
    obs:
      robot0_eef_pos:
        shape:
        - 3
      robot0_eef_quat:
        shape:
        - 4
      robot0_eye_in_hand_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      robot0_gripper_qpos:
        shape:
        - 2
      robot1_eef_pos:
        shape:
        - 3
      robot1_eef_quat:
        shape:
        - 4
      robot1_eye_in_hand_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      robot1_gripper_qpos:
        shape:
        - 2
      shouldercamera0_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      shouldercamera1_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
  task_name: transport
task_name: transport_image
training:
  checkpoint_every: 50
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 3100
  resume: true
  rollout_every: 50
  sample_every: 5
  sample_max_batch: 128
  seed: 42
  tqdm_interval_sec: 1.0
  val_every: 1
val_dataloader:
  batch_size: 128
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: false
